import mongoose, { Document, Schema } from "mongoose";

// export type PaymentStatus =
//   | "PENDING"
//   | "SUCCESS"
//   | "FAILED"
//   | "CANCELLED";

// export interface IPaymentOrder extends Document {
//   orderId: string;

//   userId: mongoose.Types.ObjectId;

//   amount: number;

//   currency: string;

//   status: PaymentStatus;

//   // Paytm details
//   txnToken?: string;
//   txnId?: string;

//   paymentMode?: string;

//   responseCode?: string;
//   responseMessage?: string;

//   // Paytm callback data
//   callbackReceivedAt?: Date;

//   createdAt: Date;
//   updatedAt: Date;
// }

const paymentOrderSchema = new Schema(
  {
    // Our application's unique order ID
    orderId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    // User who created the payment
    // userId: {
    //   type: Schema.Types.ObjectId,
    //   ref: "User",
    //   required: true,
    //   index: true,
    // },

    // Amount that customer has to pay
    amount: {
      type: Number,
      required: true,
      min: 0,
    },

    currency: {
      type: String,
      required: true,
      default: "INR",
    },

    // Current payment state
    status: {
      type: String,
      enum: ["PENDING", "SUCCESS", "FAILED", "CANCELLED"],
      default: "PENDING",
      index: true, //MongoDB is field par index banayega, taaki is field ke basis par search/query faster ho sake.
    },

    // Generated by Paytm during transaction initiation
    txnToken: {
      type: String,
    },

    // Paytm transaction ID
    txnId: {
      type: String,
      sparse: true,
      index: true,
    },

    paymentMode: {
      type: String,
    },

    responseCode: {
      type: String,
    },

    responseMessage: {
      type: String,
    },

    callbackReceivedAt: {
      type: Date,
    },
  },
  {
    timestamps: true,
  },
);

const PaymentOrder = mongoose.model("PaymentOrder", paymentOrderSchema);
export default PaymentOrder;
