import mongoose, { Document, Schema } from "mongoose";

// export type TransactionStatus =
//   | "PENDING"
//   | "SUCCESS"
//   | "FAILED"
//   | "CANCELLED";

// export type PaymentGateway = "PAYTM";

// export interface IPaymentTransaction extends Document {
//   transactionId: string;

//   paymentOrderId: mongoose.Types.ObjectId;

//   orderId: string;

//   userId: mongoose.Types.ObjectId;

//   gateway: PaymentGateway;

//   gatewayTransactionId?: string;

//   amount: number;

//   currency: string;

//   status: TransactionStatus;

//   paymentMethod?: string;

//   responseCode?: string;

//   responseMessage?: string;

//   gatewayResponse?: Record<string, unknown>;

//   createdAt: Date;
//   updatedAt: Date;
// }

const paymentTransactionSchema = new Schema(
  {
    // Our internal transaction ID
    transactionId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    // Reference to PaymentOrder document
    paymentOrderId: {
      type: Schema.Types.ObjectId,
      ref: "PaymentOrder",
      required: true,
      index: true,
    },

    // Our application's order ID
    orderId: {
      type: String,
      required: true,
      index: true,
    },

    // User who made the payment
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    // Payment gateway
    gateway: {
      type: String,
      enum: ["PAYTM"],
      required: true,
      default: "PAYTM",
    },

    // Transaction ID generated by Paytm
    gatewayTransactionId: {
      type: String,
      sparse: true,
      index: true,
    },

    // Amount in paise
    // Example: ₹500 = 50000
    amount: {
      type: Number,
      required: true,
      min: 0,
    },

    currency: {
      type: String,
      required: true,
      default: "INR",
    },

    // Current transaction status
    status: {
      type: String,
      enum: ["PENDING", "SUCCESS", "FAILED", "CANCELLED"],
      required: true,
      default: "PENDING",
      index: true,
    },

    // UPI, Credit Card, Debit Card, Net Banking etc.
    paymentMethod: {
      type: String,
      trim: true,
    },

    // Paytm response code
    responseCode: {
      type: String,
      trim: true,
    },

    // Paytm response message
    responseMessage: {
      type: String,
      trim: true,
    },

    // Store only required/non-sensitive gateway response data
    gatewayResponse: {
      type: Schema.Types.Mixed,
    },
  },
  {
    timestamps: true,
  },
);

const PaymentTransaction = mongoose.model(
  "PaymentTransaction",
  paymentTransactionSchema,
);
export default PaymentTransaction;
